### ISSUE TITLE
Can you please add feature 

### ISSUE THREAD

**Issue by meetakshiaggarwal** [seidme/flxng#39]
- select mention by enter
- add highlight in the dropdown - active class and be able to change by keyboard up/down class

**Comment by seidme** [comment]
@meetakshiaggarwal The features you're requesting are for the menu component which is there just for demo purposes. It's not part of the @flxng/mentions package. It's up to you to use whatever menu component you want.

You're more than welcome to contribute/update the menu component in the demo/showcase app with the features you suggested though.

Thank you
